### ISSUE TITLE
Set Decimal Places

### ISSUE THREAD

**Issue by Al-Imran** [mmoller2k/Float64#6]
How to set decimal places (dp) while printing?

I see there's a declaration as `void setDecs(int n);` in _Float64.h_ and a definition in _Float64ops.cpp_. By default, it seems the dp is set to be 4 - `int f64::aft_point = 4;` in line 6. But, I don't see this cpp being used anywhere! Maybe I missed it. How would we call this method during printing?

**Comment by mmoller2k** [comment]
I don't recall, but would suggest that you look at my calculator project
also on github. It uses the float64 library and might serve as an example
of what you need.

**Comment by Al-Imran** [comment]
Thanks. This solved my issue.
